---
defaults: &defaults
  buildpacks:
    - java_buildpack_offline
  stack: cflinuxfs3
  memory: 1G
  timeout: 180
  instances: 1
  maximum_health_check_timeout: 300
  env:
    SPRING_PROFILES_ACTIVE: stage
    TZ: America/Chicago
    DT_TAGS: ArcherID:7134790 ComponentID:c600 
    JAVA_OPTS: >
      -XX:MaxGCPauseMillis=200
      -XX:MaxMetaspaceSize=256M
      -Xms1024m
      -Xmx1024m
      -XX:NewSize=512m
      -XX:MaxNewSize=512m
      -Djava.security.egd=file:///dev/urandom
      -Dhttp.proxyHost=inetgw.aa.com
      -Dhttp.proxyPort=9093
      -Dhttps.proxyHost=inetgw.aa.com
      -Dhttps.proxyPort=9093
  services:
    - mosaic-receipts
    - splunk-drains
    - mosaic-receipts-wifi
        
    
