mosaic:
  inflight:
    schema:
      name: CERT_INFLIGHT_SRVCS_VW
      #name: PROD_INFLIGHT_SRVCS_VW
  ticket:
    schema:
      name: PROD_TCN_RECPT_VW

logging:
  level:
    org.springframework.jdbc.core: INFO
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    com.teradata.jdbc: DEBUG