mosaic:
  inflight:
    schema:
      name: PROD_INFLIGHT_SRVCS_VW
  ticket:
    schema:
      name: PROD_TCN_RECPT_VW

management:
  endpoint:
    health:
      show-details: "NEVER"
  health:
    db:
      enabled: false
      
spring:
  jdbc:
    template:
      query-timeout: 30
      
logging:
  level:
    org.springframework.jdbc: INFO
    com.zaxxer.hikari: INFO      