server:
  port: ${port:8094}

spring:
  datasource:
    driver-class-name: com.teradata.jdbc.TeraDriver
    url: '${vcap.services.mosaic-receipts.credentials.uri:jdbc:teradata://EDTDC.aa.com/database=CERT_INFLIGHT_SRVCS_VW,charset=UTF8}'
    username: ${vcap.services.mosaic-receipts.credentials.username:MOSTDSTEAMRECEIPTSAPP01}
    password: '${vcap.services.mosaic-receipts.credentials.password:Receipts@4Cloud}'

    hikari:
      minimumIdle: 15
      maximumPoolSize: 20
      idleTimeout: 0
      connectionTimeout: 20000
      max-lifetime: 1800000
      health-check-properties:
        expected99thPercentileMs: 0
        connectivityCheckTimeoutMs: 600000
  jdbc:
    template:
      query-timeout: 25

mosaic:
  inflight:
    schema:
      name: CERT_INFLIGHT_SRVCS_VW
  ticket:
    schema:
      name: CERT_TCN_RECPT_VW

airport:
  service:
    url: https://cdn.flyaa.aa.com/api/places/airports/v1.0?Client-Id=Receipts-MS

logging:
  level:
    root: ERROR
    com.aa.fly.receipts: INFO
    org.springframework.jdbc.core: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: DEBUG
    com.teradata.jdbc: DEBUG

  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M %.36X{XTransactionID} - %msg%n'
    
loglib:
  requestHeadersToLog: X-Client-ID,X-Transaction-ID
  responseHeadersToLog: X-Client-ID,X-Transaction-ID
