server:
  port: ${port:8094}

spring:
  datasource:
    driver-class-name: com.teradata.jdbc.TeraDriver
    jdbcUrl: 'jdbc:teradata://EDTDP.aa.com/'
    username: 
    password: 

    hikari:
      minimumIdle: 15
      maximumPoolSize: 20
      idleTimeout: 0
      connectionTimeout: 20000
      max-lifetime: 1800000
      health-check-properties:
        expected99thPercentileMs: 0
        connectivityCheckTimeoutMs: 600000

  datasourcewifi:
    driver-class-name: com.teradata.jdbc.TeraDriver
    jdbcUrl: 'jdbc:teradata://EDTDP.aa.com/'
    username: 
    password: 

# Disabled actuator DB health check which sends [SELECT 1] to Teradata.
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  health:
    db:
      enabled: false

mosaic:
  inflight:
    schema:
      name: PROD_INFLIGHT_SRVCS_VW
  ticket:
    schema:
      name: PROD_TCN_RECPT_VW
  data:
    history:
      month: 18

airport:
  service:
    url: https://cdn.flyaa.aa.com/api/places/airports/v1.0?Client-Id=Receipts-MS

logging:
  level:
    root: ERROR
    com.aa.fly.receipts: INFO
    org.springframework.jdbc: TRACE
    com.zaxxer.hikari: TRACE

  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M %.36X{XTransactionID} - %msg%n'
    
loglib:
  requestHeadersToLog: X-Client-ID,X-Transaction-ID
  responseHeadersToLog: X-Client-ID,X-Transaction-ID
