CREATE SCHEMA IF NOT EXISTS CERT_TCN_VW;
CREATE SCHEMA IF NOT EXISTS CERT_INFLIGHT_SRVCS_VW;

CREATE TABLE IF NOT EXISTS CERT_TCN_VW.TCN_TICKET_FARE_CONSTRC (
    FARE_TTL_CURNCY_CD  VARCHAR(10),
    TICKET_NBR_TXT VARCHAR(50) NOT NULL,
    FARE_TTL_AMT VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS CERT_INFLIGHT_SRVCS_VW.WIFI_SUBSCR_PURCHS (
    SUBSCR_ORDER_ID  VARCHAR(10),
    PURCHS_TMS VARCHAR(10),
    PROD_NM VARCHAR(40),
    PROD_PRICE VARCHAR(10),
    CURNCY_CD VARCHAR(10),
    TAX_AMT VARCHAR(10),
    NET_PRICE VARCHAR(10),
    LAST_4_DIGIT VARCHAR(10),
    CC_TYPE_CD VARCHAR(10),
    CARD_HLDR_LAST_NM VARCHAR(30),
    INFO_SRC_TYPE_CD VARCHAR(10)
);
